security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        database_users:
            entity: { class: App\Entity\User, property: username }

    firewalls:
        main:
            pattern: ^/
            anonymous: true
            stateless: true
            guard:
              authenticators:
                - 'my_cellar.security.token_authenticator'

    access_control:
        - { path: ^/api/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
