services:
  data_fixtures.processor.user:
    class: AppBundle\DataFixtures\Processor\UserProcessor
    arguments:
      - '@security.password_encoder'
    tags: [ { name: fidry_alice_data_fixtures.processor } ]
