version: 2
jobs:
    build:
        machine: true
        working_directory: ~/barrels
        steps:
            - checkout
            - run:
                name: Prepare cache
                command: |
                    set -x
                    touch .php_cs.cache
            - restore_cache:
                name: Restore PHP CS Fixer cache
                key: php-cs-fixer-{{ checksum ".php_cs.cache" }}
            - run:
                name: pip install
                command: pip install --upgrade pip && pip install -r requirements.txt
            - run:
                name: Build and start infrastructure
                command: fab start
            - run:
                name: Check coding standards
                command: fab cs_fix:True
    deploy:
        docker:
            - image: buildpack-deps:trusty
        steps:
            - checkout
            - run:
                name: Deploy master to Heroku
                command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master
