version: '2'
services:

  php:
    build: ../services/php-fpm
    env_file: ./current.env
    ports:
      - 9000:9000
    volumes:
      - ../..:/var/www/mycellar
      - ../../logs/mycellar:/var/www/mycellar/var/logs
    links:
      - db
      - memcached

  db:
    image: mariadb
    env_file: ./current.env
    volumes:
      - ../../logs/mariadb:/var/log/mysql
      - ../../data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306

  nginx:
    build: ../services/nginx
    env_file: ./current.env
    ports:
      - 80:80
    links:
      - php
    volumes_from:
      - php
    volumes:
      - ../../logs/nginx/:/var/log/nginx

  memcached:
    build: ../services/memcached
    env_file: ./current.env

  elk:
    image: willdurand/elk
    env_file: ./current.env
    ports:
      - 81:80
    volumes:
      - ../../data/elk/logstash:/etc/logstash
      - ../../data/elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
      - php
      - nginx