services:
  db:
    env_file: ./current.env
    image: mariadb
    ports: ['3306:3306']
    volumes: ['../../logs/mariadb:/var/log/mysql', '../../data/mariadb:/var/lib/mysql']
  elk:
    env_file: ./current.env
    image: willdurand/elk
    ports: ['81:80']
    volumes: ['../../data/elk/logstash:/etc/logstash', '../../data/elk/logstash/patterns:/opt/logstash/patterns']
    volumes_from: [php, nginx]
  memcached: {build: ../services/memcached, env_file: ./current.env}
  nginx:
    build: ../services/nginx
    env_file: ./current.env
    links: [php]
    ports: ['80:80']
    volumes: ['../../logs/nginx/:/var/log/nginx']
    volumes_from: [php]
  php:
    build: ../services/php-fpm
    env_file: ./current.env
    links: [db, memcached]
    ports: ['9000:9000']
    volumes: ['../..:/var/www/mycellar', '../../logs/mycellar:/var/www/mycellar/var/logs']
version: '2'
