App\Entity\Wine:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: ['name', 'designation', 'vintage', 'classificationLevel', 'batch', 'winemaker'], ignoreNull: false, message: 'wine.not_unique' }
    - App\Validator\Constraints\ValidDesignation: { message: 'wine.designation.not_valid' }
    - App\Validator\Constraints\ValidRegion: { message: 'wine.region.not_valid' }
  properties:
    name:
      - NotBlank: { message: 'wine.name.required' }
    designation:
      - NotBlank: { message: 'wine.designation.required' }
    color:
      - NotBlank: { message: 'wine.color.required' }
      - Choice: { callback: ['App\Reference\Colors', 'getConstants'], message: 'wine.color.not_valid' }
    country:
      - NotBlank: { message: 'wine.country.required' }
      - Country: { message: 'wine.country.not_valid' }
    drinkFrom:
      - Date: { message: 'wine.drink_from.valid_date' }
    drinkTo:
      - Date: { message: 'wine.drink_to.valid_date' }
    climaxFrom:
      - Date: { message: 'wine.climax_from.valid_date' }
    climaxTo:
      - Date: { message: 'wine.climax_to.valid_date' }
    alcoholDegree:
      - GreaterThanOrEqual: { value: 0, message: 'wine.alcohol_degree.no_negative' }
    temperature:
      - GreaterThanOrEqual: { value: 0, message: 'wine.temperature.no_negative' }
    category:
      - NotBlank: { message: 'wine.category.required' }
      - Choice: { callback: ['App\Reference\Categories', 'getConstants'], message: 'wine.category.not_valid' }
    varietals:
      - All:
        - Choice: { callback: ['App\Reference\Varietals', 'getConstants'], message: 'wine.varietals.not_valid' }
    rating:
      - Range: { min: 1, max: 5, invalidMessage: 'wine.rating.between_1_and_5' }
