version: '2'
services:

  php-base:
    build:
      context: ../services/php-base
      args:
        BARRELS_UID: ${BARRELS_UID}
    image: barrels_basephp
    command: echo 'Base php container'

  php:
    build: ../services/php
    depends_on:
      - php-base
    links:
      - db
    ports:
      - 80:80
    volumes:
      - ../..:/var/www:cached

  db:
    image: mariadb
    env_file: ./current.env
    volumes:
      - ../../logs/mariadb:/var/log/mysql
      - ../../data/mariadb:/var/lib/mysql
    ports:
      - 3306:3306

  elk:
    image: willdurand/elk
    env_file: ./current.env
    ports:
      - 81:80
    volumes:
      - ../../elk/logstash:/etc/logstash:cached
      - ../../elk/logstash/patterns:/opt/logstash/patterns:cached
    volumes_from:
      - php
