services:
  db:
    env_file: ./current.env
    image: mariadb
    ports: ['3306:3306']
    volumes: ['../../logs/mariadb:/var/log/mysql', '../../data/mariadb:/var/lib/mysql']
  elk:
    env_file: ./current.env
    image: willdurand/elk
    ports: ['81:80']
    volumes: ['../../elk/logstash:/etc/logstash:cached', '../../elk/logstash/patterns:/opt/logstash/patterns:cached']
    volumes_from: [php]
  php:
    build: ../services/php
    depends_on: [php-base]
    links: [db]
    volumes: ['../..:/var/www:cached']
  php-base:
    build:
      args: {BARRELS_UID: '${BARRELS_UID}'}
      context: ../services/php-base
    command: echo 'Base php container'
    image: barrels_basephp
version: '2'
