<?php

declare(strict_types=1);

namespace App\Reference;

class Designations
{
    public const DESIGNATIONS = [
        'AU' => [
            'Chardonnay',
            'Shiraz',
        ],
        'ES' => [
            'Castilla la Mancha',
            'Montsant',
            'Priorat',
            'Ribera Del Duero',
            'Rioja',
            'Rueda',
        ],
        'FR' => [
            'Alsace' => [
                'Alsace',
                'Alsace grand cru',
                'Crémant d\'Alsace',
            ],
            'Armagnac' => [
                'Comté Tolosan',
                'Floc de Gascogne',
                'Landes',
            ],
            'Beaujolais' => [
                'Beaujolais',
                'Beaujolais-villages',
                'Brouilly',
                'Chénas',
                'Chiroubles',
                'Comtés Rhodaniens',
                'Côte-de-Brouilly',
                'Fleurie',
                'Juliénas',
                'Morgon',
                'Moulin à vent',
                'Régnié',
                'Saint-Amour',
                'Saône-et-Loire',
            ],
            'Bordeaux' => [
                'Atlantique',
                'Barsac',
                'Blaye',
                'Bordeaux',
                'Bordeaux supérieur',
                'Cadillac',
                'Canon Fronsac',
                'Cérons',
                'Côte de Blaye',
                'Côtes de Bordeaux',
                'Côtes de Bordeaux-Saint-Macaire',
                'Côtes de Bourg',
                'Crémant de Bordeaux',
                'Entre-deux-mers',
                'Fronsac',
                'Graves',
                'Graves de Vayres',
                'Graves supérieures',
                'Haut-Médoc',
                'Lalande-de-Pomerol',
                'Listrac-Médoc',
                'Loupiac',
                'Lussac-Saint-Émilion',
                'Margaux',
                'Médoc',
                'Montagne-Saint-Émilion',
                'Moulis',
                'Neac',
                'Pauillac',
                'Périgord',
                'Pessac-Léognan',
                'Pomerol',
                'Premières Côtes de Bordeaux',
                'Puisseguin-Saint-Émilion',
                'Saint-Émilion',
                'Saint-Émilion grand cru',
                'Saint-Estèphe',
                'Saint-Georges-Saint-Émilion',
                'Saint-Julien',
                'Sainte-Croix-du-Mont',
                'Sainte-Foy-Bordeaux',
                'Sauternes',
            ],
            'Bourgogne' => [
                'Aloxe-Corton',
                'Auxey-Duresses',
                'Bâtard-Montrachet',
                'Beaune',
                'Bienvenues-Bâtard-Montrachet',
                'Blagny',
                'Bonnes-Mares',
                'Bourgogne',
                'Bourgogne aligoté',
                'Bourgogne mousseux',
                'Bourgogne Passe-tout-grains',
                'Bouzeron',
                'Chablis',
                'Chablis grand cru',
                'Chambertin',
                'Chambertin-Clos de Bèze',
                'Chambolle-Musigny',
                'Chapelle-Chambertin',
                'Charlemagne',
                'Charmes-Chambertin',
                'Chassagne-Montrachet',
                'Chevalier-Montrachet',
                'Chorey-lès-Beaune',
                'Clos de la Roche',
                'Clos de Tart',
                'Clos de Vougeot',
                'Clos des Lambrays',
                'Clos Saint-Denis',
                'Corton',
                'Corton-Charlemagne',
                'Côte de Beaune',
                'Côte de Beaune-villages',
                'Côte de Nuits-villages',
                'Coteaux bourguignons',
                'Coteaux de l\'Auxois',
                'Coteaux de Tannay',
                'Crémant de Bourgogne',
                'Criots-Bâtard-Montrachet',
                'Échezeaux',
                'Fixin',
                'Gevrey-Chambertin',
                'Givry',
                'Grands-Échezeaux',
                'Griotte-Chambertin',
                'Irancy',
                'La grande rue',
                'La Romanée',
                'La Tâche',
                'Ladoix',
                'Latricières-Chambertin',
                'Mâcon',
                'Maranges',
                'Marsannay',
                'Mazis-Chambertin',
                'Mazoyères-Chambertin',
                'Mercurey',
                'Meursault',
                'Montagny',
                'Monthélie',
                'Montrachet',
                'Morey-Saint-Denis',
                'Musigny',
                'Nuits-Saint-Georges',
                'Pernand-Vergelesses',
                'Petit-Chablis',
                'Pommard',
                'Pouilly-Fuissé',
                'Pouilly-Loché',
                'Pouilly-Vinzelles',
                'Puligny-Montrachet',
                'Richebourg',
                'Romanée-Conti',
                'Romanée-Saint-Vivant',
                'Ruchottes-Chambertin',
                'Rully',
                'Saint-Aubin',
                'Saint-Bris',
                'Saint-Romain',
                'Saint-Véran',
                'Sainte-Marie-la-Blanche',
                'Santenay',
                'Saône-et-Loire',
                'Savigny-lès-Beaune',
                'Viré-Clessé',
                'Volnay',
                'Vosne-Romanée',
                'Vougeot',
                'Yonne',
            ],
            'Champagne' => [
                'Champagne',
                'Coteaux champenois',
                'Coteaux de Coiffy',
                'Haute-Marne',
                'Rosé des Riceys',
            ],
            'Cognac' => [
                'Atlantique',
                'Pineau des Charentes',
                'Charentais',
            ],
            'Jura' => [
                'Arbois',
                'Château-Chalon',
                'Côtes du Jura',
                'Crémant du Jura',
                'Franche-Comté',
                'L\'étoile',
                'Macvin du Jura',
            ],
            'Languedoc-Roussillon' => [
                'Ariège',
                'Aude',
                'Banyuls',
                'Banyuls grand cru',
                'Cabardès',
                'Cévennes',
                'Cité de Carcassonne',
                'Clairette de Bellegarde',
                'Clairette du Languedoc',
                'Collioure',
                'Corbières',
                'Corbières-Boutenac',
                'Costières de Nîmes',
                'Côte vermeille',
                'Coteaux d\'Ensérune',
                'Coteaux de Narbonne',
                'Coteaux de Peyriac',
                'Coteaux du Libron',
                'Coteaux du Pont du Gard',
                'Côtes catalanes',
                'Côtes de Thau',
                'Côtes de Thongue',
                'Côtes du Brian',
                'Côtes du Roussillon',
                'Côtes du Roussillon villages',
                'Crémant de Limoux',
                'Duché d\Uzès',
                'Faugères',
                'Fitou',
                'Gard',
                'Grand Roussillon',
                'Haute vallée de l\'Aude',
                'Haute vallée de l\'Orb',
                'Languedoc',
                'Le pays cathare',
                'Limoux',
                'Malepère',
                'Maury',
                'Minervois',
                'Minervois-La Livinière',
                'Muscat de Frontignan',
                'Muscat de Lunel',
                'Muscat de Mireval',
                'Muscat de Rivesaltes',
                'Muscat de Saint-Jean-de-Minervois',
                'Pays d\'Hérault',
                'Pays d\'Oc',
                'Rivesaltes',
                'Sable de Camargue',
                'Saint-Chinian',
                'Saint-Guilhem-le-Désert',
                'Vallée du Paradis',
                'Vallée du Torgan',
                'Vicomté d\'Aumelas',
            ],
            'Loire' => [
                'Anjou',
                'Anjou villages',
                'Anjou villages Brissac',
                'Anjou-Coteaux de la Loire',
                'Bonnezeaux',
                'Bourgueil',
                'Cabernet d\'Anjou',
                'Cabernet de Saumur',
                'Calvados',
                'Châteaumeillant',
                'Cheverny',
                'Chinon',
                'Comtés rhodaniens',
                'Côte roannaise',
                'Coteaux d\'Ancenis',
                'Coteaux de l\'Aubance',
                'Coteaux de Saumur',
                'Coteaux du Cher et de l\'Arnon',
                'Coteaux du Giennois',
                'Coteaux du Layon',
                'Coteaux du Loir',
                'Coteaux du Vendômois',
                'Côtes d\'Auvergne',
                'Côtes de la Charité',
                'Côtes du Forez',
                'Cour-Cheverny',
                'Crémant de Loire',
                'Fiefs vendéens',
                'Gros Plant du pays nantais',
                'Haut-Poitou',
                'Haute-Vienne',
                'Jasnières',
                'Menetou-Salon',
                'Montlouis-sur-Loire',
                'Muscadet',
                'Muscadet Coteaux de la Loire',
                'Muscadet Côtes de Grandlieu',
                'Muscadet Sèvre et Maine',
                'Orléans',
                'Orléans-Cléry',
                'Pouilly-fumé',
                'Pouilly-sur-Loire',
                'Puy-de-Dôme',
                'Quarts de Chaume',
                'Quincy',
                'Reuilly',
                'Rosé d\'Anjou',
                'Rosé de Loire',
                'Saint-Nicolas-de-Bourgueil',
                'Saint-Pourçain',
                'Sancerre',
                'Saumur',
                'Saumur-Champigny',
                'Savennières',
                'Touraine',
                'Touraine Noble Joué',
                'Urfé',
                'Val de Loire',
                'Valençay',
                'Vouvray',
            ],
            'Lorraine' => [
                'Côtes de Meuse',
                'Côtes de Toul',
                'Moselle',
            ],
            'Provence-Corse' => [
                'Ajaccio',
                'Alpes-de-Haute-Provence',
                'Alpes-Maritimes',
                'Alpilles',
                'Bandol',
                'Bellet',
                'Bouches-du-Rhone',
                'Cassis',
                'Corse',
                'Coteaux d\'Aix-en-Provence',
                'Coteaux varois en Provence',
                'Côtes de Provence',
                'Hautes-Alpes',
                'Ile de Beauté',
                'Les Baux de Provence',
                'Maures',
                'Méditerranée',
                'Mont Caume',
                'Muscat du Cap-Corse',
                'Palette',
                'Patrimonio',
                'Pierrevert',
                'Var',
            ],
            'Rhône' => [
                'Ardèche',
                'Beaumes de Venise',
                'Bouches-du-Rhone',
                'Cévennes',
                'Château-Grillet',
                'Châteauneuf-du-Pape',
                'Châtillon-en-Diois',
                'Clairette de Die',
                'Collines rhodaniennes',
                'Comtés rhodaniens',
                'Condrieu',
                'Cornas',
                'Côte Rôtie',
                'Coteaux de Die',
                'Coteaux des Baronnies',
                'Coteaux du Lyonnais',
                'Coteaux du Pont du Gard',
                'Côtes du Rhône',
                'Côtes du Rhône villages',
                'Côtes du Vivarais',
                'Crémant de Die',
                'Crozes-Hermitage',
                'Drôme',
                'Duché d\'Uzès',
                'Gard',
                'Gigondas',
                'Grignan-les-Adhémar',
                'Hermitage',
                'Lirac',
                'Luberon',
                'Méditerranée',
                'Muscat de Beaumes-de-Venise',
                'Rasteau',
                'Sable de Camargue',
                'Saint-Joseph',
                'Saint-Péray',
                'Tavel',
                'Vacqueyras',
                'Vaucluse',
                'Ventoux',
                'Vinsobres',
            ],
            'Savoie-Bugey' => [
                'Bugey',
                'Comtés Rhodaniens',
                'Coteaux de l\'Ain',
                'Isère',
                'Roussette de Savoie',
                'Roussette du Bugey',
                'Savoie',
                'Seyssel',
                'Vin des Allobroges',
            ],
            'Sud-Ouest' => [
                'Agenais',
                'Ariège',
                'Atlantique',
                'Aveyron',
                'Béarn',
                'Bergerac',
                'Brulhois',
                'Buzet',
                'Cahors',
                'Comté Tolosan',
                'Coteaux de Glanes',
                'Coteaux du Quercy',
                'Côtes de Bergerac',
                'Côtes de Duras',
                'Côtes de Gascogne',
                'Côtes de Millau',
                'Côtes de Montravel',
                'Côtes du Lot',
                'Côtes du Tarn',
                'Côtes du Marmandais',
                'Entraygues - Le Fel',
                'Estaing',
                'Fronton',
                'Gaillac',
                'Gaillac premières côtes',
                'Gers',
                'Haut-Montravel',
                'Irouléguy',
                'Jurançon',
                'Lavilledieu',
                'Madiran',
                'Marcillac',
                'Monbazillac',
                'Montravel',
                'Pacherenc du Vic-Bilh',
                'Pécharmant',
                'Périgord',
                'Rosette',
                'Saint-Mont',
                'Saint-Sardos',
                'Saussignac',
                'Thézac-Perricard',
                'Tursan',
                'Vins de la Corrèze',
            ],
        ],
        'HU' => [
            'Tokay',
        ],
        'IT' => [
            'Barbera d\'Asti',
            'Barbaresco',
            'Barolo',
            'Barua',
            'Brunello di Montalcino',
            'Chianti classico',
            'Chianti',
            'Montepulciano d\'Abruzzo',
            'Nebbiolo Langhe',
            'Nero',
            'Roero Arneis',
            'Rosso di Montalcino',
            'Salento rosso',
            'Torrione',
            'Toscane IGT' => 'Toscane IGT',
            'Vigneti delle Dolomiti',
            'Vino Nobile di Montepulciano',
        ],
        'NZ' => [
            'Chardonnay',
        ],
        'ZA' => [
            'Pinotage',
        ],
    ];

    public static function getAll()
    {
        return self::DESIGNATIONS;
    }

    public static function getByCountry(string $country)
    {
        if (!\array_key_exists($country, self::DESIGNATIONS)) {
            return [];
        }

        return self::DESIGNATIONS[$country];
    }

    public static function getByCountryAndRegion(string $country, string $region)
    {
        $byCountry = self::getByCountry($country);
        if (!\array_key_exists($region, $byCountry)) {
            return [];
        }

        return $byCountry[$region];
    }

    public static function getFrenchRegions()
    {
        return \array_keys(self::DESIGNATIONS['FR']);
    }
}
