<?php

declare(strict_types=1);

namespace App\Reference;

class Varietals
{
    public static function getConstants()
    {
        return [
            'Abondant',
            'Abouriou',
            'Admirable de Courtiller',
            'Aglianico',
            'Airén',
            'Albana',
            'Albariño',
            'Alcañon',
            'Aleatico',
            'Alicante-henri-bouschet',
            'Aligoté',
            'Alphonse-lavallée',
            'Altesse',
            'Amigne',
            'Angevine Oberlin',
            'Aramon',
            'Aranel',
            'Arbane',
            'Arbois',
            'Arinarnoa',
            'Arinto',
            'Arneis',
            'Arriloba',
            'Arrouya',
            'Arvine',
            'Arrufiac',
            'Auxerrois',
            'Baco blanc',
            'Baco noir',
            'Baga',
            'Balochin',
            'Barbarossa',
            'Barbera',
            'Baroque',
            'Bergeron',
            'Black Hamburg',
            'Blanc Verdan',
            'Blaufränkisch',
            'Bogazkere',
            'Bombino',
            'Bonarda',
            'Bovale',
            'Bouchet',
            'Bourboulenc',
            'Brachetto',
            'Brunello',
            'Bual',
            'Cabernet',
            'Cabernet franc',
            'Cabernet sauvignon',
            'Canaiolo',
            'Cannonau',
            'Carcajolo blanc',
            'Carcajolo noir',
            'Cardinal',
            'Carignan',
            'Carménère',
            'Carricante',
            'Castellaro',
            'Catarratto',
            'César',
            'Chambourcin',
            'Chancellor',
            'Chardonnay',
            'Chasselas',
            'Chasselas de Jérusalem',
            'Chasselas doré de Fontainebleau',
            'Chasselas de Moissac',
            'Chasselas de Thomery',
            'Chatus',
            'Chelois',
            'Chenin',
            'Ciliegiolo',
            'Cinsault',
            'Clairette',
            'Claverie',
            'Clinton',
            'Colombard',
            'Colorino',
            'Corbèse',
            'Cornalin',
            'Cortese',
            'Corvina',
            'Côt',
            'Counoise',
            'Croatina',
            'Crussin',
            'Czabah',
            'Dabouki',
            'Danube',
            'Dattier de Beyrouth',
            'Dindarella',
            'Diolinoir',
            'Dobričić',
            'Dolcetto',
            'Duras',
            'Durif',
            'Falanghina',
            'Fendant',
            'Fer Servadou',
            'Fiano',
            'Folle-Blanche',
            'Frankenthal, chasselas de Jérusalem',
            'Frankonia',
            'Frappato di Vittoria',
            'Frankovka',
            'Freisa',
            'Friulano',
            'Furmint',
            'Feteasca',
            'Gaglioppo',
            'Gamay',
            'Gamay de Chaudenay',
            'Gamay Fréaux',
            'Gamza',
            'Garganega',
            'Garanoir',
            'Gewürztraminer',
            'Gouais',
            'Graciano',
            'Grechetto',
            'Greco',
            'Grenache',
            'Grenache blanc',
            'Grenache gris',
            'Grenache noir',
            'Grignolino',
            'Grolleau',
            'Groppello bianco',
            'Groppello gentile',
            'Groppello di Mocasina',
            'Groppello di Santo Stefano',
            'Gros Colman',
            'Gros Manseng',
            'Gros noir des Béni-Abbès (Algérie)',
            'Gros vert',
            'Gutedel',
            'Grüner Veltliner',
            'Hárslevelü',
            'Hibou',
            'Humagne blanche',
            'Humagne rouge',
            'Incrocio Manzoni',
            'Jacquère',
            'Jacquez',
            'Jaoumet',
            'Johannisberg',
            'Joubertin',
            'Kadarka',
            'Kalecik Karası',
            'Kékfrankos',
            'Kéknyelü',
            'Kerner',
            'Klevener',
            'Koshu',
            'Lagrein',
            'Lambrusco',
            'Lemberger',
            'Liliorila',
            'Loureiro',
            'Macabeo',
            'Maccabeu blanc',
            'Madeleine Oberlin',
            'Malaga blanc',
            'Malbec',
            'Malvasia',
            'Malvoisie',
            'Malvasio bianco',
            'Mammolo',
            'Marsanne',
            'Mauzac blanc',
            'Mavro',
            'Mavrud',
            'Melon',
            'Melon de Bourgogne',
            'Merlot',
            'Merlot noir',
            'Merlot blanc',
            'Meslier',
            'Meunier',
            'Millot Léon',
            'Minnella',
            'Molette blanche',
            'Molinara',
            'Mondeuse',
            'Montepulciano',
            'Moristel',
            'Morrastel',
            'Moscato',
            'Mourvèdre',
            'Müller-Thurgau',
            'Muscadelle',
            'Muscadet',
            'Muscardin',
            'Muscat',
            'Muscat blanc à petits grains',
            'Muscat d\'Alexandrie',
            'Muscat d\'Espagne',
            'Muscat de Hambourg',
            'Muscat d\'Italie',
            'Muscat noir',
            'Muscat romain',
            'Narince',
            'Nebbiolo',
            'Négrette',
            'Negroamaro',
            'nerello Cappuccio',
            'Nerello mantellato',
            'Nerello mascalese',
            'Nerettia cuneese',
            'Neretto di Bairo',
            'Nero d\'Avola',
            'Nielluccio',
            'Noir de Listan',
            'Nonay',
            'Noah',
            'Odjaleschi',
            'Okuzgozu',
            'Olivette blanche',
            'Olivette noire',
            'Ondenc',
            'Païen',
            'Palomino',
            'Pamid',
            'Parraleta',
            'Pascal blanc',
            'Pecorino',
            'Pedro Ximénez',
            'Pelara',
            'Péloursin',
            'Perdea',
            'Periquita',
            'Perle de Csaba',
            'Persan',
            'Petit Courbu',
            'Petit manseng',
            'Petit verdot',
            'Petit meslier',
            'Petite syrah',
            'Petite arvine',
            'Picardan',
            'Picolit',
            'Piquepoul',
            'Pignatello',
            'Pignoletto',
            'Pineau d\'Aunis',
            'Pinotage',
            'Pinot auxerrois',
            'Pinot blanc',
            'Pinot bianco',
            'Pinot gris',
            'Pinot grigio',
            'Pinot meunier',
            'Pinot noir',
            'Pinot noir précoce',
            'Plavac mali',
            'Pointu de vimines',
            'Poulsard',
            'Primitivo',
            'Prin blanc',
            'Prosecco',
            'Prugnolo Gentile',
            'Rabo',
            'Refosco',
            'Regent',
            'Regina',
            'Reine des vignes',
            'Ribier',
            'Riesling',
            'Riesling italien',
            'Rogettaz',
            'Rognin',
            'Rolle',
            'Romain ou césar',
            'Romorantin',
            'Rondinella',
            'Roussanne',
            'Roussette',
            'Sabal kanskoï',
            'Saint-François',
            'Saint-Jacques',
            'Saint-Jeannet',
            'Saint Laurent',
            'Sagrantino',
            'Sangiovese',
            'Saperavi',
            'Sauvignon blanc',
            'Sauvignon',
            'Savagnin',
            'Savagnin blanc',
            'Scheurebe',
            'Schiava',
            'Sciacarello',
            'Sémillon',
            'Sercial',
            'Servant',
            'Seyval blanc',
            'Skadarka',
            'Steen',
            'Sultanine',
            'Sylvaner',
            'Syrah',
            'Tannat',
            'Tempranillo',
            'Teroldego',
            'Terret noir',
            'Tibouren',
            'Tocai',
            'Tokay',
            'Torrontés',
            'Touriga franca',
            'Touriga nacional',
            'Traminer',
            'Trebbiano ou Ugni blanc',
            'Trepat',
            'Tressallier',
            'Trousseau',
            'Valensy noir',
            'Verdal',
            'Verdaou',
            'Verdejo',
            'Verdelho',
            'Verdicchio',
            'Vernaccia',
            'Verpillin',
            'Vidal blanc',
            'Viognier',
            'Viura',
            'Vranac',
            'Xynisteri',
            'Zibbibo',
            'Zinfandel',
            'Zweigelt',
        ];
    }
}
